In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%load_ext sql

In [2]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:SecureP%40sw0rd%21123@localhost:3306/united_nations

In [3]:
%%sql

SELECT
    *
FROM
    Access_to_Basic_Services
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00'))]

In [5]:
%%sql
# Add your code here
SELECT
    *
FROM
    united_nations.Access_to_Basic_Services
LIMIT 30;

 * mysql+pymysql://root:***@localhost:3306/united_nations
30 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2020, Decimal('95.00'), Decimal('98.00'), Decimal('18.755666'), Decimal('171.08'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2015, Decimal('89.67'), Decimal('96.67'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2016, Decimal('90.33'), Decimal('96.67'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2017, Decimal('91.00'), Decimal('97.33'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2018, Decimal('91.33'), Decimal('97.33'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2019, Decimal('91.67'), Decimal('97.33'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2020, Decimal('92.67'), Decimal('97.67'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2015, Decimal('80.33'), Decimal('95.00'), Decimal('8.524063'), Decimal('8.27'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2016, Decimal('81.33'), Decimal('95.33'), Decimal('8.725318'), Decimal('6.99'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2017, Decimal('82.33'), Decimal('95.67'), Decimal('8.925525'), Decimal('7.54'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2018, Decimal('83.33'), Decimal('95.67'), Decimal('9.128132'), Decimal('7.77'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2019, Decimal('85.00'), Decimal('96.33'), Decimal('9.337003'), Decimal('8.30'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Tajikistan', 2020, Decimal('85.00'), Decimal('96.33'), Decimal('9.543207'), Decimal('8.13'), Decimal('138790.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2015, Decimal('97.67'), Decimal('97.33'), Decimal('5.766431'), Decimal('35.80'), Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2016, Decimal('98.00'), Decimal('98.00'), Decimal('5.868561'), Decimal('36.17'), Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2017, Decimal('98.67'), Decimal('98.00'), Decimal('5.968383'), Decimal('37.93'), Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2018, Decimal('99.33'), Decimal('98.67'), Decimal('6.065066'), Decimal('40.77'), Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2019, Decimal('100.00'), Decimal('99.33'), Decimal('6.158420'), Decimal('45.23'), Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Turkmenistan', 2020, Decimal('100.00'), Decimal('99.33'), Decimal('6.250438'), None, Decimal('469930.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2015, Decimal('97.67'), Decimal('100.00'), Decimal('31.298900'), Decimal('86.20'), Decimal('440600.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2016, Decimal('97.67'), Decimal('100.00'), Decimal('31.847900'), Decimal('86.14'), Decimal('440591.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2017, Decimal('98.00'), Decimal('100.00'), Decimal('32.388600'), Decimal('62.08'), Decimal('440588.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2018, Decimal('98.00'), Decimal('100.00'), Decimal('32.956100'), Decimal('52.63'), Decimal('440587.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2019, Decimal('98.00'), Decimal('100.00'), Decimal('33.580350'), Decimal('59.91'), Decimal('440555.00')),
 ('Central and Southern Asia', 'Central Asia', 'Uzbekistan', 2020, Decimal('98.00'), Decimal('100.00'), Decimal('34.232050'), Decimal('59.89'), Decimal('440650.00'))]

In [6]:
%%sql

SELECT
    *
FROM
    united_nations.Access_to_Basic_Services
LIMIT 10;

 * mysql+pymysql://root:***@localhost:3306/united_nations
10 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2020, Decimal('95.00'), Decimal('98.00'), Decimal('18.755666'), Decimal('171.08'), Decimal('2699700.00')),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2015, Decimal('89.67'), Decimal('96.67'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2016, Decimal('90.33'), Decimal('96.67'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2017, Decimal('91.00'), Decimal('97.33'), None, None, None),
 ('Central and Southern Asia', 'Central Asia', 'Kyrgyzstan', 2018, Decimal('91.33'), Decimal('97.33'), None, None, None)]

In [7]:
%%sql

SELECT DISTINCT
    Country_name
FROM
    united_nations.Access_to_Basic_Services
    LIMIT 20;

 * mysql+pymysql://root:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan',),
 ('Kyrgyzstan',),
 ('Tajikistan',),
 ('Turkmenistan',),
 ('Uzbekistan',),
 ('Afghanistan',),
 ('Bangladesh',),
 ('Bhutan',),
 ('India',),
 ('Iran (Islamic Republic of)',),
 ('Maldives',),
 ('Nepal',),
 ('Pakistan',),
 ('Sri Lanka',),
 ('China',),
 ("Democratic People's Republic of Korea",),
 ('Japan',),
 ('Mongolia',),
 ('Republic of Korea',),
 ('Brunei Darussalam',)]

In [8]:
%%sql

CREATE TABLE Country_list(Country VARCHAR(255));
INSERT INTO Country_list(Country)
SELECT DISTINCT
    Country_name
FROM
    united_nations.Access_to_Basic_Services;

 * mysql+pymysql://root:***@localhost:3306/united_nations
0 rows affected.
184 rows affected.

[]

In [9]:
%%sql

SELECT
    country_name,
    time_period,
    pct_managed_drinking_water_services
FROM
    united_nations.Access_to_Basic_Services
LIMIT 20;

 * mysql+pymysql://root:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan', 2015, Decimal('94.67')),
 ('Kazakhstan', 2016, Decimal('94.67')),
 ('Kazakhstan', 2017, Decimal('95.00')),
 ('Kazakhstan', 2018, Decimal('95.00')),
 ('Kazakhstan', 2019, Decimal('95.00')),
 ('Kazakhstan', 2020, Decimal('95.00')),
 ('Kyrgyzstan', 2015, Decimal('89.67')),
 ('Kyrgyzstan', 2016, Decimal('90.33')),
 ('Kyrgyzstan', 2017, Decimal('91.00')),
 ('Kyrgyzstan', 2018, Decimal('91.33')),
 ('Kyrgyzstan', 2019, Decimal('91.67')),
 ('Kyrgyzstan', 2020, Decimal('92.67')),
 ('Tajikistan', 2015, Decimal('80.33')),
 ('Tajikistan', 2016, Decimal('81.33')),
 ('Tajikistan', 2017, Decimal('82.33')),
 ('Tajikistan', 2018, Decimal('83.33')),
 ('Tajikistan', 2019, Decimal('85.00')),
 ('Tajikistan', 2020, Decimal('85.00')),
 ('Turkmenistan', 2015, Decimal('97.67')),
 ('Turkmenistan', 2016, Decimal('98.00'))]

In [10]:
%%sql

SELECT
    country_name,
    time_period,
    pct_managed_drinking_water_services AS pct_access_to_water
FROM
    united_nations.Access_to_Basic_Services
LIMIT 20

 * mysql+pymysql://root:***@localhost:3306/united_nations
20 rows affected.

[('Kazakhstan', 2015, Decimal('94.67')),
 ('Kazakhstan', 2016, Decimal('94.67')),
 ('Kazakhstan', 2017, Decimal('95.00')),
 ('Kazakhstan', 2018, Decimal('95.00')),
 ('Kazakhstan', 2019, Decimal('95.00')),
 ('Kazakhstan', 2020, Decimal('95.00')),
 ('Kyrgyzstan', 2015, Decimal('89.67')),
 ('Kyrgyzstan', 2016, Decimal('90.33')),
 ('Kyrgyzstan', 2017, Decimal('91.00')),
 ('Kyrgyzstan', 2018, Decimal('91.33')),
 ('Kyrgyzstan', 2019, Decimal('91.67')),
 ('Kyrgyzstan', 2020, Decimal('92.67')),
 ('Tajikistan', 2015, Decimal('80.33')),
 ('Tajikistan', 2016, Decimal('81.33')),
 ('Tajikistan', 2017, Decimal('82.33')),
 ('Tajikistan', 2018, Decimal('83.33')),
 ('Tajikistan', 2019, Decimal('85.00')),
 ('Tajikistan', 2020, Decimal('85.00')),
 ('Turkmenistan', 2015, Decimal('97.67')),
 ('Turkmenistan', 2016, Decimal('98.00'))]

In [11]:
%%sql

SELECT
    country_name,
    time_period,
    pct_managed_drinking_water_services AS pct_access_to_water
FROM
    united_nations.Access_to_Basic_Services
WHERE
    Time_period = 2020
LIMIT 100;

 * mysql+pymysql://root:***@localhost:3306/united_nations
100 rows affected.

[('Kazakhstan', 2020, Decimal('95.00')),
 ('Kyrgyzstan', 2020, Decimal('92.67')),
 ('Tajikistan', 2020, Decimal('85.00')),
 ('Turkmenistan', 2020, Decimal('100.00')),
 ('Uzbekistan', 2020, Decimal('98.00')),
 ('Afghanistan', 2020, Decimal('80.33')),
 ('Bangladesh', 2020, Decimal('97.67')),
 ('Bhutan', 2020, Decimal('97.33')),
 ('India', 2020, Decimal('91.00')),
 ('Iran (Islamic Republic of)', 2020, Decimal('96.67')),
 ('Maldives', 2020, Decimal('99.67')),
 ('Nepal', 2020, Decimal('90.00')),
 ('Pakistan', 2020, Decimal('90.67')),
 ('Sri Lanka', 2020, Decimal('94.33')),
 ('China', 2020, Decimal('93.67')),
 ("Democratic People's Republic of Korea", 2020, Decimal('93.33')),
 ('Japan', 2020, Decimal('99.00')),
 ('Mongolia', 2020, Decimal('81.00')),
 ('Republic of Korea', 2020, Decimal('100.00')),
 ('Brunei Darussalam', 2020, Decimal('100.00')),
 ('Cambodia', 2020, Decimal('75.33')),
 ('Indonesia', 2020, Decimal('92.00')),
 ("Lao People's Democratic Republic", 2020, Decimal('86.67')),
 ('Malaysia', 2020, Decimal('95.33')),
 ('Myanmar', 2020, Decimal('85.67')),
 ('Philippines', 2020, Decimal('94.00')),
 ('Singapore', 2020, Decimal('100.00')),
 ('Thailand', 2020, Decimal('100.00')),
 ('Timor-Leste', 2020, Decimal('87.00')),
 ('Viet Nam', 2020, Decimal('97.33')),
 ('Bermuda', 2020, Decimal('100.00')),
 ('Canada', 2020, Decimal('99.00')),
 ('Greenland', 2020, Decimal('100.00')),
 ('Saint Pierre and Miquelon', 2020, Decimal('91.00')),
 ('United States of America', 2020, Decimal('100.00')),
 ('Barbados', 2020, Decimal('99.00')),
 ('British Virgin Islands', 2020, Decimal('100.00')),
 ('Cuba', 2020, Decimal('96.33')),
 ('Dominican Republic', 2020, Decimal('95.00')),
 ('Guadeloupe', 2020, Decimal('100.00')),
 ('Haiti', 2020, Decimal('65.00')),
 ('Jamaica', 2020, Decimal('90.33')),
 ('Martinique', 2020, Decimal('100.00')),
 ('Montserrat', 2020, Decimal('98.00')),
 ('Puerto Rico', 2020, Decimal('100.00')),
 ('Saint Barthélemy', 2020, Decimal('100.00')),
 ('Saint Lucia', 2020, Decimal('97.00')),
 ('Saint Martin (French Part)', 2020, Decimal('100.00')),
 ('Trinidad and Tobago', 2020, Decimal('99.00')),
 ('United States Virgin Islands', 2020, Decimal('99.00')),
 ('Belize', 2020, Decimal('98.33')),
 ('Costa Rica', 2020, Decimal('100.00')),
 ('El Salvador', 2020, Decimal('97.00')),
 ('Guatemala', 2020, Decimal('94.00')),
 ('Honduras', 2020, Decimal('95.33')),
 ('Mexico', 2020, Decimal('99.33')),
 ('Nicaragua', 2020, Decimal('79.33')),
 ('Panama', 2020, Decimal('92.67')),
 ('Argentina', 2020, Decimal('100.00')),
 ('Bolivia (Plurinational State of)', 2020, Decimal('90.67')),
 ('Brazil', 2020, Decimal('98.33')),
 ('Chile', 2020, Decimal('100.00')),
 ('Colombia', 2020, Decimal('94.67')),
 ('Ecuador', 2020, Decimal('94.00')),
 ('Falkland Islands (Malvinas)', 2020, Decimal('91.00')),
 ('French Guiana', 2020, Decimal('94.00')),
 ('Guyana', 2020, Decimal('96.67')),
 ('Paraguay', 2020, Decimal('99.67')),
 ('Peru', 2020, Decimal('90.33')),
 ('Suriname', 2020, Decimal('98.00')),
 ('Uruguay', 2020, Decimal('98.00')),
 ('Venezuela (Bolivarian Republic of)', 2020, Decimal('94.00')),
 ('Algeria', 2020, Decimal('93.33')),
 ('Egypt', 2020, Decimal('99.33')),
 ('Libya', 2020, Decimal('100.00')),
 ('Morocco', 2020, Decimal('88.33')),
 ('Sudan', 2020, Decimal('62.33')),
 ('Tunisia', 2020, Decimal('97.00')),
 ('Armenia', 2020, Decimal('100.00')),
 ('Azerbaijan', 2020, Decimal('95.67')),
 ('Bahrain', 2020, Decimal('100.00')),
 ('Cyprus', 2020, Decimal('100.00')),
 ('Georgia', 2020, Decimal('96.67')),
 ('Iraq', 2020, Decimal('97.67')),
 ('Israel', 2020, Decimal('100.00')),
 ('Jordan', 2020, Decimal('98.33')),
 ('Kuwait', 2020, Decimal('100.00')),
 ('Lebanon', 2020, Decimal('93.00')),
 ('Oman', 2020, Decimal('87.67')),
 ('Qatar', 2020, Decimal('100.00')),
 ('Saudi Arabia', 2020, Decimal('100.00')),
 ('State of Palestine', 2020, Decimal('98.33')),
 ('Syrian Arab Republic', 2020, Decimal('93.67')),
 ('Türkiye', 2020, Decimal('96.67')),
 ('United Arab Emirates', 2020, Decimal('100.00')),
 ('Yemen', 2020, Decimal('63.00')),
 ('Australia', 2020, Decimal('100.00')),
 ('New Zealand', 2020, Decimal('100.00')),
 ('Fiji', 2020, Decimal('93.67')),
 ('New Caledonia', 2020, Decimal('99.00'))]

In [12]:
%%sql

SELECT
    country_name,
    time_period,
    pct_managed_drinking_water_services AS pct_access_to_water
FROM
    united_nations.Access_to_Basic_Services
WHERE
    Time_period = 2020
ORDER BY pct_access_to_water
LIMIT 10;

 * mysql+pymysql://root:***@localhost:3306/united_nations
10 rows affected.

[('Central African Republic', 2020, Decimal('38.33')),
 ('Democratic Republic of the Congo', 2020, Decimal('47.67')),
 ('South Sudan', 2020, Decimal('48.33')),
 ('Angola', 2020, Decimal('52.33')),
 ('Chad', 2020, Decimal('52.67')),
 ('Burkina Faso', 2020, Decimal('53.33')),
 ('Madagascar', 2020, Decimal('56.33')),
 ('Papua New Guinea', 2020, Decimal('56.67')),
 ('Somalia', 2020, Decimal('57.33')),
 ('Niger', 2020, Decimal('57.33'))]